# https://docs.getdbt.com/docs/core/connect-data-platform/profiles.yml

project_transformation:
  outputs:

    dev:
      type: postgres
      host: {{ mage_secret_var('postgres_host') }}
      user: {{ mage_secret_var('postgres_user') }}
      password: {{ mage_secret_var('postgres_password') }}
      port: {{ mage_secret_var('postgres_port') }}
      dbname: {{ mage_secret_var('postgres_db') }}
      schema: analytics
      threads: 20
      

  target: dev
